### ISSUE TITLE
Impossible to enable Pretty-mail

### ISSUE THREAD

**Issue by Hiobi** [FriendsOfFlarum/pretty-mail#3]
### Instructions (MUST READ FIRST)

Before we can address your issues and concerns with the behavior of our work, we require every bit of detail from you to the fullest extent of this form. If this form is not properly filled out to it's entirity, we, ReFlar, reserve the right to close your issue due to lack of information thereof as well as not following instructions.

* [x] By agreeing to these terms, you can simply leave this checkbox checked.

### Please Mentally Go Over the Following Items Before Filling Out this Form:

* Can you reproduce this problem in debug mode? YES
* Are you running the latest version of this extension? YES
* Is your Flarum up-to-date? YES

### Description

Hi,
When I try to enable the extension, I got an error and I cannot enabling it. :)

### Steps to Reproduce

1. Install the extension
2. Enable extension in admin panel
3. got an error; extension cannot be enable

**Expected Behavior:** Enabling extension

**Actual Behavior:** Cannot enable extension

## Technical Details

- Version of Flarum (x.y.z): 0.1.0-beta.8.1
- Version of extension (x.y.z): 0.1.0-beta.3
- [OPTIONAL] Website URL where the bug is visible (https://example.com): https://forum.nefald.fr
- The webserver you are running (Apache, Nginx, etc): Nginx
- PHP version (x.y.z): 7.3.5-1
- Hosted environment (Shared, VPS, etc): Dedicated server
- Hosting provider (https://some-amazing-provider.com): online.net

## Flarum Info

```
Flarum core 0.1.0-beta.8.1
PHP version: 7.3.5-1+0~20190503093827.38+stretch~1.gbp60a41b
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, Reflection, SPL, sodium, session, standard, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, json, exif, mysqli, newrelic, pdo_mysql, pdo_sqlite, Phar, posix, readline, recode, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xmlreader, xmlrpc, xmlwriter, xsl, zip, Zend OPcache
+---------------------------------+-----------------+--------+
| Flarum Extensions               |                 |        |
+---------------------------------+-----------------+--------+
| ID                              | Version         | Commit |
+---------------------------------+-----------------+--------+
| flarum-statistics               | v0.1.0-beta.8   |        |
| flarum-sticky                   | v0.1.0-beta.8   |        |
| flarum-subscriptions            | v0.1.0-beta.8   |        |
| flarum-suspend                  | v0.1.0-beta.8   |        |
| flarum-tags                     | v0.1.0-beta.8.2 |        |
| flarum-flags                    | v0.1.0-beta.8.1 |        |
| flarum-emoji                    | v0.1.0-beta.8   |        |
| flarum-bbcode                   | v0.1.0-beta.8   |        |
| flarum-approval                 | v0.1.0-beta.8   |        |
| flarum-mentions                 | v0.1.0-beta.8.1 |        |
| flarum-markdown                 | v0.1.0-beta.8   |        |
| flarum-lock                     | v0.1.0-beta.8   |        |
| flarum-likes                    | v0.1.0-beta.8.1 |        |
| flarum-pusher                   | v0.1.0-beta.8.1 |        |
| milescellar-lang-french         | v1.2.1          |        |
| noriods-auto-more               | 0.3.0           |        |
| flagrow-direct-links            | 0.2.0           |        |
| flagrow-terms                   | 0.3.1           |        |
| flagrow-users-list              | 0.1.2           |        |
| reflar-polls                    | 1.3.2           |        |
| flagrow-upload                  | 0.7.1           |        |
| flagrow-byobu                   | 0.2.2           |        |
| fof-socialprofile               | 0.1.1           |        |
| fof-pages                       | 0.2.2           |        |
| fof-formatting                  | 0.1.2           |        |
| kvothe-pipetables               | 1.0.9           |        |
| fof-links                       | 0.1.1           |        |
| kvothe-keyboard-shortcuts       | v0.1.0          |        |
| fof-default-group               | 0.1.0           |        |
| flagrow-analytics               | 0.8.0           |        |
| jordanjay29-summaries           | 0.3.1           |        |
| flagrow-user-directory          | 0.2.1           |        |
| amaurycarrade-syndication       | v0.2.0          |        |
| fof-merge-discussions           | 0.2.0           |        |
| flagrow-split                   | 0.3.2           |        |
| reflar-reactions                | 1.0.0-beta.5.2  |        |
| fof-prevent-necrobumping        | 0.1.3           |        |
| michaelbelgium-discussion-views | v0.1.0-beta.8.2 |        |
| rooaaar-lang-french-extended    | v1.0.4          |        |
| flagrow-mason                   | 0.3.1           |        |
| fajuu-contactbutton             | v2.0            |        |
| fof-sentry                      | 0.1.1           |        |
| michaelbelgium-profile-views    | v0.1.0-beta-8-3 |        |
| fof-recaptcha                   | 0.1.0           |        |
| reflar-cookie-consent           | 0.2.0           |        |
| fof-secure-https                | v0.1.0          |        |
| fof-spamblock                   | 0.2.1           |        |
| reflar-pwned-passwords          | 0.2.0           |        |
| flagrow-bazaar                  | 0.3.10          |        |
| fof-transliterator              | 0.1.1           |        |
| reflar-stopforumspam            | 0.1.5           |        |
| flagrow-sitemap                 | 0.2.0           |        |
+---------------------------------+-----------------+--------+
Base URL: https://forum.nefald.fr

```

## Log Files

```
Too few arguments to function Illuminate\Filesystem\Filesystem::{closure}(), 1 passed and exactly 2 expected


Exception(most recent call first)

ArgumentCountError: Too few arguments to function Illuminate\Filesystem\Filesystem::{closure}(), 1 passed and exactly 2 expected
#49 vendor/reflar/pretty-mail/migrations/2018_04_17_202287_add_default_template_to_settings.php(7): {closure}
#48 vendor/illuminate/filesystem/Filesystem.php(0): call_user_func
#47 vendor/flarum/core/src/Database/Migrator.php(197): runClosureMigration
#46 vendor/flarum/core/src/Database/Migrator.php(130): runUp
#45 vendor/flarum/core/src/Database/Migrator.php(113): runMigrationList
#44 vendor/flarum/core/src/Database/Migrator.php(87): run
#43 vendor/flarum/core/src/Extension/ExtensionManager.php(241): migrate
#42 vendor/flarum/core/src/Extension/ExtensionManager.php(127): enable
#41 vendor/flarum/core/src/Api/Controller/UpdateExtensionController.php(49): handle
#40 vendor/flarum/core/src/Http/RouteHandlerFactory.php(40): Flarum\Http\{closure}
#39 vendor/flarum/core/src/Http/Middleware/DispatchRoute.php(67): process
#38 vendor/zendframework/zend-stratigility/src/Next.php(52): handle
#37 vendor/reflar/stopforumspam/src/Middleware/RegisterMiddleware.php(75): process
#36 vendor/zendframework/zend-stratigility/src/Next.php(52): handle
#35 vendor/reflar/pwned-passwords/src/Middleware/CheckPassword.php(66): process
#34 vendor/zendframework/zend-stratigility/src/Next.php(52): handle
#33 vendor/fof/secure-https/src/Middlewares/ContentSecurityPolicyMiddleware.php(21): process
#32 vendor/zendframework/zend-stratigility/src/Next.php(52): handle
#31 vendor/fof/sentry/src/Middleware/HandleErrorsWithSentry.php(19): process
#30 vendor/zendframework/zend-stratigility/src/Next.php(52): handle
#29 vendor/flagrow/terms/src/Middlewares/RegisterMiddleware.php(59): process
#28 vendor/zendframework/zend-stratigility/src/Next.php(52): handle
#27 vendor/flarum/core/src/Http/Middleware/SetLocale.php(51): process
#26 vendor/zendframework/zend-stratigility/src/Next.php(52): handle
#25 vendor/flarum/core/src/Http/Middleware/AuthenticateWithHeader.php(55): process
#24 vendor/zendframework/zend-stratigility/src/Next.php(52): handle
#23 vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(34): process
#22 vendor/zendframework/zend-stratigility/src/Next.php(52): handle
#21 vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(52): process
#20 vendor/zendframework/zend-stratigility/src/Next.php(52): handle
#19 vendor/flarum/core/src/Http/Middleware/StartSession.php(62): process
#18 vendor/zendframework/zend-stratigility/src/Next.php(52): handle
#17 vendor/flarum/core/src/Api/Middleware/FakeHttpMethods.php(31): process
#16 vendor/zendframework/zend-stratigility/src/Next.php(52): handle
#15 vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(29): process
#14 vendor/zendframework/zend-stratigility/src/Next.php(52): handle
#13 vendor/flarum/core/src/Api/Middleware/HandleErrors.php(42): process
#12 vendor/zendframework/zend-stratigility/src/Next.php(52): handle
#11 vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(83): process
#10 vendor/middlewares/request-handler/src/RequestHandler.php(84): process
#9 vendor/zendframework/zend-stratigility/src/Next.php(52): handle
#8 vendor/middlewares/base-path-router/src/BasePathRouter.php(97): process
#7 vendor/zendframework/zend-stratigility/src/Next.php(52): handle
#6 vendor/middlewares/base-path/src/BasePath.php(53): process
#5 vendor/zendframework/zend-stratigility/src/Next.php(52): handle
#4 vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(83): process
#3 vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(72): handle
#2 vendor/zendframework/zend-httphandlerrunner/src/RequestHandlerRunner.php(95): run
#1 vendor/flarum/core/src/Http/Server.php(46): listen
#0 public/index.php(22): null
```

Thanks ! :D

**Comment by dsevillamartin** [comment]
This extension hasn't been updated to beta 8 yet, sorry.
